export {default as Home} from './Home'
export {default as Matchday} from './Matchday'
export {default as Player} from './Player'
export {default as League} from './League'
export {default as Team} from './Team'